second-challenge/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_Iso_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

first-challenge/src/globalValueSets/Countries_Iso_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries Iso Code</masterLabel>
</GlobalValueSet>

second-challenge/src/classes/ProductService.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductService
-- - Description: Provide functions regarding Product__c
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/04/2019       Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

public class ProductService {
	public ProductService() {
		
	}
	
	
	public ProductDTO loadRelatedProduct(Id caseId){
		ProductDTO dataTransferObject;
		try{
			Case contextCase = [SELECT ContactId FROM Case WHERE Id =: caseId];
			Contact relatedContact = [SELECT Product__c, Home_Country__c FROM Contact WHERE Id =: contextCase.contactId];
			ContactWrapper contact = new ContactWrapper(relatedContact);
			ProductWrapper product = contact.getYourProduct();
			dataTransferObject = new ProductDTO(product);
		} catch(QueryException ex){
			dataTransferObject = new ProductDTO(null);
		}


		return dataTransferObject;
	}
}