second-challenge/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_Iso_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

first-challenge/src/globalValueSets/Countries_Iso_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries Iso Code</masterLabel>
</GlobalValueSet>

second-challenge/src/classes/ContactWrapper.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ContactWrapper
-- - Description: Encapsulates the contact and it&#39;s attributes
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/05/2019       Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

public class ContactWrapper  {

	private Contact contact {get; set;}

	private ProductWrapper relatedProduct {get; set;}

	public ContactWrapper(Contact c) {
		ProductInformationContext.contextContact = this;
		this.contact = c;
		loadProductInfo();
	}
	
	private void loadProductInfo(){
		try{
			Product__c product = [SELECT Name, Id FROM Product__c WHERE Id =: contact.Product__c];
			relatedProduct = new ProductWrapper(product);
		}catch(QueryException ex){
			ProductWrapper blankProduct = new ProductWrapper(new Product__c(Name = 'Empty Product'));
			relatedProduct = blankProduct;
		}

	}
	
	public ProductWrapper getYourProduct(){
		return relatedProduct;
	}

	public string getHomeCountry(){
		return contact.Home_Country__c;
	}

}