second-challenge/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <label>Home Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Countries_Iso_Code</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

first-challenge/src/globalValueSets/Countries_Iso_Code.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Countries Iso Code</masterLabel>
</GlobalValueSet>

second-challenge/src/classes/ProductServiceTest.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductServiceTest
-- - Description: Test Class for ProductService
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/05/2019        Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class ProductServiceTest
{

	@testSetup
	static void setup(){
		//Create test data here

		Product__c product = new Product__c(Name='Silver');
		insert product;

		Contact defaultContact = new Contact(Product__c = product.Id, LastName = 'Gouvea', Language__c = 'de', Home_Country__c = 'DE', Email = 'felipegouvea@n26bank.com');
		insert defaultContact;

		Case c = new Case(Origin = 'Phone', ContactId = defaultContact.Id);
		insert c;

		Case blankCase = new Case(Origin = 'Web');
		insert blankCase;
	}

	@isTest
	static void completeObjectSetTest()
	{
		// Given
		ProductService service = new ProductService();
		id targetCaseId = [SELECT Id FROM Case LIMIT 1].Id;

		// When
		Test.startTest();
		
		ProductDTO dto = service.loadRelatedProduct(targetCaseId);
		
		Test.stopTest();


		// Then
		System.assert(true);

		System.assertNotEquals(NULL, dto);
	}

	@isTest
	static void testWithBlankCase()
	{
		// Given
		ProductService service = new ProductService();
		id targetCaseId = [SELECT Id FROM Case WHERE ContactId =: NULL LIMIT 1].Id;



		// When
		Test.startTest();
		
		ProductDTO dto = service.loadRelatedProduct(targetCaseId);
		
		Test.stopTest();


		// Then
		System.assert(true);

		System.assertNotEquals(NULL, dto);
	}

}