second-challenge/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/objects/Product_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Price_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/classes/ProductInformationControllerTest.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductInformationControllerTest
-- - Description: Test class for ProductInformationController
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/05/2019	     Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class ProductInformationControllerTest
{

	@testSetup
	static void setup(){
		//Create test data here

		Product__c product = new Product__c(Name='Black');
		insert product;
		
		Product_Detail__c detail = new Product_Detail__c(Name = 'MonthlyFee', Parent_Product__c = product.Id);

		Contact defaultContact = new Contact(LastName = 'Gouvea', Language__c = 'en', Email = 'felipegouvea@n26bank.com');
		insert defaultContact;

		Case c = new Case(Origin = 'Phone', ContactId = defaultContact.Id);
		insert c;


	}

	@isTest
	static void itShould()
	{
		// Given
		Id targetId = [SELECT Id FROM Contact].Id;

		// When
		Test.startTest();
		
		ProductDTO dto = ProductInformationController.loadRelatedProduct(targetId);

		Test.stopTest();


		// Then
		System.assert(true);

		System.assertNotEquals(NULL, dto);
		System.assertEquals(1, dto.details.size());
		System.assertEquals('Monthly Fee', dto.details[0].name);
		System.assertEquals('Black', dto.productName);
	}
}