second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/objects/Product_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Price_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/classes/ProductDetailWrapperTest.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductDetailWrapperTest
-- - Description: Test class for ProductDetailWrapper
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
--       Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class ProductDetailWrapperTest
{

	@testSetup
	static void setup(){
		//Create test data here
		Product__c product = new Product__c(Name='Standard');
		insert product;

		Product_Detail__c detail = new Product_Detail__c(Parent_Product__c = product.Id);
		insert detail;
	
	}

	testMethod
	static void testCostMethods()
	{
		// Given
		Product_Detail__c detail = [SELECT Parent_Product__c FROM Product_Detail__c LIMIT 1];
		ProductDetailWrapper wrapper = new ProductDetailWrapper(detail);
		// When
		Test.startTest();
		
		decimal monthlyCost = wrapper.getMonthlyCost();
		decimal ATMFee = wrapper.getATMFee();
		decimal cardReplacementCost = wrapper.getCardReplacementCost();
		Test.stopTest();


		// Then
		System.assert(true);
		
		decimal monthlyFeeForProductRuleStandardPrice = 0;
		decimal ATMFeeForProductRuleStandardPrice = 0.017;
		decimal cardReplacementCostForProductRuleStandardPrice = 0;

		System.assertEquals(monthlyFeeForProductRuleStandardPrice, monthlyCost);
		System.assertEquals(ATMFeeForProductRuleStandardPrice, ATMFee);
		System.assertEquals(cardReplacementCostForProductRuleStandardPrice, cardReplacementCost);
	}
}