second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/objects/Product_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Price_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/classes/ProductDTOTest.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductDTOTest
-- - Description: Test class for ProductDTO
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/06/2019        Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class ProductDTOTest
{

	@testSetup
	static void setup(){
		//Create test data here
		Product__c standardProduct = new Product__c(Name='Standard');
		insert standardProduct;

		Product_Detail__c firstProductDetail = new Product_Detail__c(Name='Monthly Fee', Parent_Product__c = standardProduct.Id);
		insert firstProductDetail;


		Product__c metalProduct = new Product__c(Name='Metal');
		insert metalProduct;

		Product_Detail__c secondProductDetail = new Product_Detail__c(Name='Monthly Fee', Parent_Product__c = metalProduct.Id);
		insert secondProductDetail;
	
	}

	@isTest
	static void integrityTest()
	{
		// Given
		Product__c SProduct = [SELECT Name FROM Product__c WHERE Name = 'Standard'];
		ProductDTO standardProduct = new ProductDTO(new ProductWrapper(SProduct));
		Product__c MProduct = [SELECT Name FROM Product__c WHERE Name = 'Metal'];
		ProductDTO metalProduct = new ProductDTO(new ProductWrapper(MProduct));

		// When
		Test.startTest();
		
		string standardProductSerialized = JSON.serialize(standardProduct);
		string metalProductSerialized = JSON.serialize(metalProduct);

		Test.stopTest();


		// Then
		System.assert(true);
		System.assertNotEquals(standardProductSerialized, metalProductSerialized, 'Two different products can\'t be equals');
	}
}