second-challenge/src/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/objects/Product_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Product</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Price_Parameters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Detail</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

second-challenge/src/classes/ProductWrapperTest.cls
/* 
----------------------------------------------------------------------------------------------
-- - Company:     N26 Bank
-- - Name:        ProductWrapperTest
-- - Description: Test class for ProductWrapper
-- - @Author: Felipe Gouvea
-- ------------------------------------------------------------------------------------------
--
-- Date              Name               Version                   
----------------------------------------------------------------------------------------------
-- 05/05/2019        Felipe Gouvea      1.0         
----------------------------------------------------------------------------------------------
*/

@isTest
private class ProductWrapperTest
{

	@testSetup
	static void setup(){
		//Create test data here
		Product__c product = new Product__c(Name='Test');
		insert product;

		Product_Detail__c detail = new Product_Detail__c(Name = 'Detail Test', Parent_Product__c = product.Id);
		insert detail;
	
	}

	@isTest
	static void getNameTest(){
		// Given
		Product__c product = [SELECT Name FROM Product__c WHERE Name = 'Test' LIMIT 1];
		ProductWrapper wrapper = new ProductWrapper(product);

		// When
		Test.startTest();
		
		string productName = wrapper.getName();

		Test.stopTest();

		System.assertEquals('Test', productName);
	}

	@isTest
	static void getMonthlyCostTest(){
		// Given
		Product__c product = [SELECT Name FROM Product__c LIMIT 1];
		ProductWrapper wrapper = new ProductWrapper(product);

		// When
		Test.startTest();
		
		decimal calculatedMonthlyCost =wrapper.getMonthlyCost();

		Test.stopTest();


		// Then
		System.assert(true);
		System.assertNotEquals(NULL, calculatedMonthlyCost);
	}


	@isTest
	static void getATMFeeTest(){
		// Given
		Product__c product = [SELECT Name FROM Product__c LIMIT 1];
		ProductWrapper wrapper = new ProductWrapper(product);

		// When
		Test.startTest();
		
		decimal calculatedATMFee =wrapper.getATMFee();
		
		Test.stopTest();


		// Then
		System.assert(true);
		System.assertNotEquals(NULL, calculatedATMFee);
	}

	@isTest
	static void getCardReplacementCostTest(){
		// Given
		Product__c product = [SELECT Name FROM Product__c LIMIT 1];
		ProductWrapper wrapper = new ProductWrapper(product);

		// When
		Test.startTest();
		
		decimal cardReplacementCost = wrapper.getCardReplacementCost();
		
		Test.stopTest();


		// Then
		System.assert(true);
		System.assertNotEquals(NULL, cardReplacementCost);
	}
}